"""Train demo cancer subtype classification models."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import joblib
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.data import (  # noqa: E402
    SUBTYPES,
    align_expression_and_labels,
    generate_synthetic_demo_dataset,
)
from src.evaluate import calculate_accuracy, calculate_macro_f1, evaluate_predictions  # noqa: E402
from src.preprocessing import (  # noqa: E402
    build_preprocessing_pipeline,
    stratified_train_test_split,
)


RANDOM_SEED = 42
MODEL_PATH = Path("models") / "best_model.joblib"


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""

    parser = argparse.ArgumentParser(
        description="Train cancer subtype classification models."
    )
    parser.add_argument(
        "--demo",
        action="store_true",
        help="Train on synthetic demo data generated by src.data.",
    )
    return parser.parse_args()


def train_demo() -> dict[str, object]:
    """Train demo models and save the best full inference pipeline."""

    expression_df, labels_df = generate_synthetic_demo_dataset(
        n_samples=80,
        n_genes=40,
        random_state=RANDOM_SEED,
    )
    X, y = align_expression_and_labels(expression_df, labels_df)

    X_train, X_test, y_train, y_test = stratified_train_test_split(
        X,
        y,
        test_size=0.25,
        random_state=RANDOM_SEED,
    )

    models = {
        "Logistic Regression": LogisticRegression(
            max_iter=1000,
            random_state=RANDOM_SEED,
        ),
        "Random Forest": RandomForestClassifier(
            n_estimators=100,
            random_state=RANDOM_SEED,
        ),
    }

    results = []
    for model_name, classifier in models.items():
        model_pipeline = Pipeline(
            steps=[
                ("preprocessing", build_preprocessing_pipeline()),
                ("classifier", classifier),
            ]
        )
        model_pipeline.fit(X_train, y_train)
        predictions = model_pipeline.predict(X_test)

        results.append(
            {
                "name": model_name,
                "pipeline": model_pipeline,
                "predictions": predictions,
                "accuracy": calculate_accuracy(y_test, predictions),
                "macro_f1": calculate_macro_f1(y_test, predictions),
            }
        )

    best_result = max(results, key=lambda result: (result["macro_f1"], result["accuracy"]))

    evaluate_predictions(
        y_true=y_test,
        y_pred=best_result["predictions"],
        labels=SUBTYPES,
        output_dir=Path("outputs"),
    )

    MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(best_result["pipeline"], MODEL_PATH)

    return {
        "best_model": best_result["name"],
        "best_accuracy": best_result["accuracy"],
        "best_macro_f1": best_result["macro_f1"],
        "n_train": len(X_train),
        "n_test": len(X_test),
        "n_features": X.shape[1],
        "results": results,
    }


def print_training_summary(summary: dict[str, object]) -> None:
    """Print a concise training summary for the CLI."""

    print("Training complete")
    print(f"Samples: {summary['n_train']} train / {summary['n_test']} test")
    print(f"Features: {summary['n_features']} genes")
    print("Model comparison:")

    for result in summary["results"]:
        print(
            f"- {result['name']}: "
            f"accuracy={result['accuracy']:.3f}, "
            f"macro_f1={result['macro_f1']:.3f}"
        )

    print(
        f"Best model: {summary['best_model']} "
        f"(accuracy={summary['best_accuracy']:.3f}, "
        f"macro_f1={summary['best_macro_f1']:.3f})"
    )
    print("Saved metrics: outputs/metrics.json")
    print("Saved confusion matrix: outputs/confusion_matrix.png")
    print(f"Saved model: {MODEL_PATH}")


def main() -> None:
    """Run the training CLI."""

    args = parse_args()
    if not args.demo:
        raise SystemExit("Only demo mode is currently supported. Run: python src/train.py --demo")

    summary = train_demo()
    print_training_summary(summary)


if __name__ == "__main__":
    main()
